// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtC8peMHFflAKCyDhWrAF-2sxPn3r2_9A',
    appId: '1:622221890611:web:2b99cba421efe95c243f46',
    messagingSenderId: '622221890611',
    projectId: 'parent-student-app-590a0',
    authDomain: 'parent-student-app-590a0.firebaseapp.com',
    storageBucket: 'parent-student-app-590a0.appspot.com',
    measurementId: 'G-NXM1D6YQZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtAdyu2oEVTuWQNV1wnQWdyzNsuWWfvYM',
    appId: '1:622221890611:android:ddcce76cfdee2a08243f46',
    messagingSenderId: '622221890611',
    projectId: 'parent-student-app-590a0',
    storageBucket: 'parent-student-app-590a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKfY0v8uK6IREYfQdG_PG587fJWSwoBn4',
    appId: '1:622221890611:ios:1d4983c6a56868b2243f46',
    messagingSenderId: '622221890611',
    projectId: 'parent-student-app-590a0',
    storageBucket: 'parent-student-app-590a0.appspot.com',
    iosBundleId: 'com.example.parentStudentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKfY0v8uK6IREYfQdG_PG587fJWSwoBn4',
    appId: '1:622221890611:ios:1d4983c6a56868b2243f46',
    messagingSenderId: '622221890611',
    projectId: 'parent-student-app-590a0',
    storageBucket: 'parent-student-app-590a0.appspot.com',
    iosBundleId: 'com.example.parentStudentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtC8peMHFflAKCyDhWrAF-2sxPn3r2_9A',
    appId: '1:622221890611:web:0610492b5f0c1295243f46',
    messagingSenderId: '622221890611',
    projectId: 'parent-student-app-590a0',
    authDomain: 'parent-student-app-590a0.firebaseapp.com',
    storageBucket: 'parent-student-app-590a0.appspot.com',
    measurementId: 'G-9SC6YDSKCH',
  );

}